server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:orleydb
  jpa:
    show-sql: true

  main:
    allow-circular-references: true
  cloud:
    config:
      import-check:
        enabled: false

logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false